### PR TITLE
fix: :bug: Cannot find module '../package.json'

### LINKED ISSUE #22: Cannot find module '../package.json'
```
~/puppet-xp   test ±  git push                 
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '../package.json'
Require stack:
- ~/puppet-xp/node_modules/@chatie/git-scripts/dist/bin/pre-push.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (~/puppet-xp/node_modules/@chatie/git-scripts/dist/bin/pre-push.js:48:24)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/binsee/CodeWork/puppet-xp/node_modules/@chatie/git-scripts/dist/bin/pre-push.js'
  ]
}
Failed to exec pre-push hook script
error: failed to push some refs to 'github.com:binsee/puppet-xp.git'
```

### PR DESCRIPTION
**Pull request by binsee**
Fixes #22

### CODE REVIEW

File: bin/pre-push.ts [hunk 1]
```diff
@@ -55,7 +56,8 @@ if (refs?.[0]?.localCommit.match(/^0+$/)) {
   process.exit(0)
 }
 
-const packageVersion = require('../package.json').version
+const pkgFile = path.join(process.cwd(), 'package.json')
```
Comment (huan) [inline bin/pre-push.ts:59]: the `process.cwd()` will be depended on the Current Working Directory (CWD), which is not reliable.

It would be better to use the `__dirname` so that the path can be absolute.

**Review by huan — CHANGES_REQUESTED** [review]
Could we use `__dirname` instead of `process.cwd()` to make sure the path is not related to the CWD?

**Comment by binsee** [comment]
In this use case, `process.cwd()` would be more reliable, because we need to locate the codebase directory where the hook script is to take effect, not the directory of the hook scripts.

Example:

Test with the following code in `pre-push`:

````js
const pkgFile = path.join(process.cwd(), 'package.json')
const packageVersion = require(pkgFile).version
console.info('__filename', __filename)
console.info('__dirname', __dirname)
console.info('process.cwd()', process.cwd())
console.info('packageVersion', packageVersion)
process.exit(1)
````

- `@chatie/git-scripts` project

```bash
 binsee@localhost > ~/CodeWork/chatie-git-scripts >  binsee/issue22 ± > pwd
/Users/binsee/CodeWork/chatie-git-scripts
 binsee@localhost > ~/CodeWork/chatie-git-scripts >  binsee/issue22 ± > git push
__filename /Users/binsee/CodeWork/chatie-git-scripts/bin/pre-push.ts
__dirname /Users/binsee/CodeWork/chatie-git-scripts/bin
process.cwd() /Users/binsee/CodeWork/chatie-git-scripts
packageVersion 0.7.3
Failed to exec pre-push hook script
error: failed to push some refs to 'github.com:binsee/chatie-git-scripts.git'
````

we need:
  - `path.join(__dirname, '../package.json')`
  - `path.join(process.cwd(), 'package.json')`


- `puppet-xp` project, depends on `pre-push` hook provided by `@chatie/git-scripts`

```bash
 ✘ binsee@localhost > ~/CodeWork/puppet-xp >  test ± > pwd
/Users/binsee/CodeWork/puppet-xp
 binsee@localhost > ~/CodeWork/puppet-xp >  test ± > git push
__filename /Users/binsee/CodeWork/puppet-xp/node_modules/@chatie/git-scripts/dist/bin/pre-push.js
__dirname /Users/binsee/CodeWork/puppet-xp/node_modules/@chatie/git-scripts/dist/bin
process.cwd() /Users/binsee/CodeWork/puppet-xp
packageVersion 1.10.26
Failed to exec pre-push hook script
error: failed to push some refs to 'github.com:binsee/puppet-xp.git'
````


we need:
  - `path.join(__dirname, '../../../../../package.json')`
  - `path.join(process.cwd(), 'package.json')`


When git executes the hook, git will change the working directory to the root directory of the code base, so it is more reliable to use `process.cwd()`.

**Review by huan — APPROVED** [review]
LGTM

Thank you very much for the improvements and the explanations, appreciate it!
